FROM vllm/vllm-openai:v0.8.3

WORKDIR /app 


# ENV HF_ENDPOINT=https://hf-mirror.com
# RUN huggingface-cli download --resume-download yang31210999/Llama3.1-1B-Neo-BAAI-1000k --local-dir /models/Llama3.1-1B
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list
RUN apt update && apt install -y git
RUN pip install toml
RUN pip install pandas

RUN echo '[model]' >> conf.toml && \
    echo 'MODEL_NAME = "Llama3.1-1B"' >> conf.toml && \
    echo 'PORT = 6008' >> conf.toml

COPY vllm_start vllm_start
COPY benchmark benchmark
# ENTRYPOINT ["bash", "-c", "while true; do sleep 1000; done"]
ENTRYPOINT ["python3", "-u", "vllm_start/vllm_start_up.py"]