FROM vllm/vllm-openai:v0.8.3

WORKDIR /app

# Install dependencies
RUN pip install toml pandas datasets matplotlib

COPY vllm_start vllm_start
COPY benchmark benchmark
COPY prepare_model.sh prepare_model.sh
